const KEY='offline-ledger-users-v1', CATS=['房租水电','饮食','娱乐','交通','饮品','休闲','服饰美妆','日用','人情'];
let user=null, month=new Date().toISOString().slice(0,7);
const $=s=>document.querySelector(s), load=()=>JSON.parse(localStorage.getItem(KEY)||'{}'), save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const money=n=>'¥'+Number(n||0).toFixed(2), digest=s=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};
function render(){const u=load()[user], rs=u.records.filter(r=>r.date.slice(0,7)===month), total=rs.reduce((a,r)=>a+r.amount,0); $('#accountName').textContent=user;$('#accountAvatar').textContent=user[0].toUpperCase();$('#monthInput').value=month;$('#overviewView').innerHTML=`<div class="stats-grid"><div class="stat-card"><small>本月支出</small><strong>${money(total)}</strong><div class="trend">${rs.length} 笔记录</div></div><div class="stat-card"><small>日均支出</small><strong>${money(total/(new Date(+month.slice(0,4),+month.slice(5),0).getDate()))}</strong></div><div class="stat-card"><small>必要支出</small><strong>${money(rs.filter(r=>r.necessity==='必要').reduce((a,r)=>a+r.amount,0))}</strong></div><div class="stat-card"><small>记录状态</small><strong>${rs.length?'已记录':'暂无'}</strong></div></div><section class="panel" style="margin-top:16px"><div class="panel-head"><h3>最近记录</h3><button class="ghost-btn" data-view="records">查看全部</button></div>${rs.length?'<div class="record-list">'+rs.slice(0,8).map(r=>`<div class="record-row"><div class="record-main"><strong>${r.major} · ${r.minor||'未分类'}</strong><small>${r.date.replace('T',' ')} · ${r.necessity}</small></div><div class="record-amount">${money(r.amount)}</div></div>`).join('')+'</div>':'<div class="empty">这个月还没有记录</div>'}</section>`; $('#overviewView [data-view]').onclick=()=>{view('records')};}
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#viewTitle').textContent={overview:'月度总览',records:'明细记录',analysis:'分类分析',months:'月份归档'}[v];if(v==='records') renderRecords();else if(v==='analysis') renderAnalysis();else if(v==='months') renderMonths();else render();}
function renderRecords(){const rs=load()[user].records.filter(r=>r.date.slice(0,7)===month);$('#recordsView').innerHTML='<section class="panel"><div class="panel-head"><h3>明细记录</h3><button class="primary-btn" id="recordAdd">+ 记一笔</button></div><div class="table-wrap"><table><thead><tr><th>日期</th><th>分类</th><th>必要性</th><th>金额</th></tr></thead><tbody>'+ (rs.length?rs.map(r=>`<tr><td>${r.date.replace('T',' ')}</td><td>${r.major} · ${r.minor||'未分类'}</td><td>${r.necessity}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">这个月还没有记录</div></td></tr>')+'</tbody></table></div></section>';$('#recordAdd').onclick=()=>$('#openAddBtn').click();}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#monthInput').onchange=e=>{month=e.target.value;render()};$('#openAddBtn').onclick=()=>{$('#dateInput').value=new Date().toISOString().slice(0,16);$('#expenseDialog').showModal()};$('#closeExpenseBtn').onclick=()=>$('#expenseDialog').close();
$('#expenseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),a=Number(f.get('amount'));if(!(a>=0))return alert('请输入金额');const all=load();all[user].records.push({date:f.get('date'),amount:a,major:f.get('major'),minor:f.get('minor'),necessity:f.get('necessity'),id:Date.now()});save(all);$('#expenseDialog').close();e.target.reset();render()};
$('#majorInput').innerHTML=CATS.map(c=>`<option>${c}</option>`).join('');$('#minorInput').innerHTML='<option>未分类</option>';

const allUsers=load(); user=localStorage.getItem('offline-ledger-active') || '我的账本'; if(!allUsers[user]) allUsers[user]={records:[]}; save(allUsers); document.querySelector('#authScreen').classList.add('hidden'); document.querySelector('#app').classList.remove('hidden'); render();
function renderAnalysis(){const rs=load()[user].records.filter(r=>r.date.slice(0,7)===month);const totals=Object.fromEntries(CATS.map(c=>[c,rs.filter(r=>r.major===c).reduce((a,r)=>a+r.amount,0)]));const total=rs.reduce((a,r)=>a+r.amount,0);$('#analysisView').innerHTML='<section class="panel"><div class="panel-head"><h3>分类分析</h3><span class="muted">'+month+'</span></div><div class="category-grid">'+CATS.map(c=>'<div class="category-card"><h4>'+c+'</h4><div class="category-meta"><span>支出</span><strong>'+money(totals[c])+'</strong></div><div class="progress"><i style="width:'+(total?Math.min(100,totals[c]/total*100):0)+'%"></i></div></div>').join('')+'</div></section>';}
+function renderMonths(){const rs=load()[user].records;const months=[...new Set(rs.map(r=>r.date.slice(0,7)).concat([month]))].sort().reverse();$('#monthsView').innerHTML='<section class="panel"><div class="panel-head"><h3>月份归档</h3><span class="muted">按月查看记录</span></div><div class="month-grid">'+months.map(m=>{const list=rs.filter(r=>r.date.slice(0,7)===m), t=list.reduce((a,r)=>a+r.amount,0);return '<button class="month-card" data-month="'+m+'" style="text-align:left"><h4>'+m+'</h4><div class="month-meta"><span>'+list.length+' 笔记录</span><strong>'+money(t)+'</strong></div></button>';}).join('')+'</div></section>';document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month=b.dataset.month;view('overview')});}