const STORAGE_KEY = "offline-ledger-users-v1";
const ACCOUNT = "我的账本";
const CATEGORIES = {
  "房租水电": ["房租", "水费", "电费", "燃气", "物业"], "饮食": ["早餐", "午餐", "晚餐", "买菜", "零食"],
  "娱乐": ["电影", "游戏", "演出", "会员"], "交通": ["公交", "地铁", "打车", "加油", "停车"],
  "饮品": ["咖啡", "奶茶", "果汁", "酒水"], "休闲": ["旅行", "健身", "兴趣", "户外"],
  "服饰美妆": ["服装", "鞋包", "护肤", "美妆"], "日用": ["家居", "清洁", "数码", "药品"], "人情": ["红包", "礼物", "聚会"]
};
const TITLES = { overview: "月度总览", records: "明细记录", analysis: "分类分析", months: "月份归档" };
const COLORS = ["#1f8f78", "#e09f3e", "#457b9d", "#d66565", "#5f7f72", "#9c6f9e", "#5c8dbe", "#a17c52", "#6b7280"];
const $ = (selector) => document.querySelector(selector);
let selectedMonth = localMonth(); let activeView = "overview";
function localMonth() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; }
function localDateTime() { const now = new Date(); return new Date(now - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function readStore() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}"); } catch { return {}; } }
function currentAccount() { const store = readStore(); if (!store[ACCOUNT]) store[ACCOUNT] = { records: [], budgets: {} }; store[ACCOUNT].records ||= []; store[ACCOUNT].budgets ||= {}; localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); return { store, account: store[ACCOUNT] }; }
function persist(store) { localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); }
function money(value) { return `¥${Number(value || 0).toFixed(2)}`; }
function monthText(value) { const [year, month] = value.split("-"); return `${year}年${Number(month)}月`; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char])); }
function monthRecords() { return currentAccount().account.records.filter((record) => record.date.slice(0, 7) === selectedMonth).sort((a, b) => b.date.localeCompare(a.date)); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2000); }
function setView(view) { activeView = view; $("#viewTitle").textContent = TITLES[view]; document.querySelectorAll(".nav-item").forEach((button) => button.classList.toggle("active", button.dataset.view === view)); document.querySelectorAll(".view").forEach((section) => section.classList.toggle("active", section.id === `${view}View`)); renderActiveView(); window.scrollTo({ top: 0, behavior: "instant" }); }
function renderActiveView() { $("#monthInput").value = selectedMonth; if (activeView === "overview") renderOverview(); if (activeView === "records") renderRecords(); if (activeView === "analysis") renderAnalysis(); if (activeView === "months") renderMonths(); }
function renderOverview() {
  const records = monthRecords(), total = records.reduce((sum, record) => sum + record.amount, 0), dailyTotal = records.filter((record) => !record.oneTime).reduce((sum, record) => sum + record.amount, 0), necessary = records.filter((record) => record.necessity === "必要").reduce((sum, record) => sum + record.amount, 0), days = new Date(Number(selectedMonth.slice(0, 4)), Number(selectedMonth.slice(5)), 0).getDate();
  $("#overviewView").innerHTML = `<div class="stats-grid"><article class="stat-card stat-primary"><small>本月支出</small><strong>${money(total)}</strong><span>${records.length} 笔记录</span></article><article class="stat-card"><small>日均支出</small><strong>${money(dailyTotal / days)}</strong><span>不含大额单次支出</span></article><article class="stat-card"><small>必要支出</small><strong>${money(necessary)}</strong><span>占比 ${total ? Math.round(necessary / total * 100) : 0}%</span></article><article class="stat-card"><small>剩余天数</small><strong>${selectedMonth === localMonth() ? Math.max(0, days - new Date().getDate()) : 0}</strong><span>${monthText(selectedMonth)}</span></article></div><section class="panel recent-panel"><div class="panel-head"><h2>最近记录</h2><button class="ghost-btn" data-open-records>查看全部</button></div>${recordCards(records.slice(0, 6))}</section>`;
  $("[data-open-records]")?.addEventListener("click", () => setView("records"));
}
function recordCards(records) { if (!records.length) return `<div class="empty"><strong>这个月还没有记录</strong><span>点击“记一笔”开始使用</span></div>`; return `<div class="record-list">${records.map((record) => `<article class="record-row"><div class="record-main"><strong>${escapeHtml(record.major)} · ${escapeHtml(record.minor || "未分类")}</strong><small>${record.date.replace("T", " ")} · ${escapeHtml(record.necessity)}${record.oneTime ? " · 单次支出" : ""}</small>${record.note ? `<small>${escapeHtml(record.note)}</small>` : ""}</div><div class="record-side"><strong>${money(record.amount)}</strong>${record.id ? `<button class="delete-btn" data-delete="${escapeHtml(record.id)}">删除</button>` : ""}</div></article>`).join("")}</div>`; }
function renderRecords() { const records = monthRecords(); $("#recordsView").innerHTML = `<section class="panel"><div class="panel-head"><div><h2>${monthText(selectedMonth)}</h2><span class="muted">共 ${records.length} 笔</span></div><button class="primary-btn" data-add-record>+ 记一笔</button></div>${recordCards(records)}</section>`; $("[data-add-record]")?.addEventListener("click", openExpenseDialog); document.querySelectorAll("[data-delete]").forEach((button) => button.addEventListener("click", () => deleteRecord(button.dataset.delete))); }
function renderAnalysis() {
  const records = monthRecords(), total = records.reduce((sum, record) => sum + record.amount, 0), { account } = currentAccount(); account.budgets[selectedMonth] ||= {};
  $("#analysisView").innerHTML = `<section class="panel"><div class="panel-head"><div><h2>分类预算</h2><span class="muted">${monthText(selectedMonth)}</span></div><strong>${money(total)}</strong></div><div class="category-grid">${Object.keys(CATEGORIES).map((category, index) => { const spent = records.filter((record) => record.major === category).reduce((sum, record) => sum + record.amount, 0), budget = Number(account.budgets[selectedMonth][category] || 0), percent = budget ? Math.min(100, spent / budget * 100) : 0; return `<article class="category-card"><div class="category-title"><span class="dot" style="background:${COLORS[index]}"></span><h3>${category}</h3><strong>${money(spent)}</strong></div><div class="progress"><i style="width:${percent}%"></i></div><div class="budget-row"><input type="number" inputmode="decimal" min="0" step="0.01" value="${budget || ""}" placeholder="设置月预算" data-budget="${category}"><button class="ghost-btn" data-save-budget="${category}">保存</button></div></article>`; }).join("")}</div></section>`;
  document.querySelectorAll("[data-save-budget]").forEach((button) => button.addEventListener("click", () => saveBudget(button.dataset.saveBudget)));
}
function renderMonths() { const records = currentAccount().account.records, months = [...new Set(records.map((record) => record.date.slice(0, 7)).concat(selectedMonth))].sort().reverse(); $("#monthsView").innerHTML = `<section class="panel"><div class="panel-head"><div><h2>月份归档</h2><span class="muted">点击月份查看详情</span></div></div><div class="month-grid">${months.map((value) => { const list = records.filter((record) => record.date.slice(0, 7) === value), total = list.reduce((sum, record) => sum + record.amount, 0), necessary = list.filter((record) => record.necessity === "必要").reduce((sum, record) => sum + record.amount, 0); return `<button class="month-card${value === selectedMonth ? " selected" : ""}" data-month="${value}"><span>${monthText(value)}</span><strong>${money(total)}</strong><small>${list.length} 笔 · 必要支出 ${total ? Math.round(necessary / total * 100) : 0}%</small></button>`; }).join("")}</div></section>`; document.querySelectorAll("[data-month]").forEach((button) => button.addEventListener("click", () => { selectedMonth = button.dataset.month; setView("overview"); })); }
function fillMinorCategories() { const major = $("#majorInput").value; $("#minorInput").innerHTML = CATEGORIES[major].map((minor) => `<option>${minor}</option>`).join("") + `<option value="__custom">自定义...</option>`; $("#customMinorField").classList.add("hidden"); }
function openExpenseDialog() { $("#dateInput").value = localDateTime(); $("#expenseDialog").showModal(); setTimeout(() => $("#amountInput").focus(), 100); }
function deleteRecord(id) { if (!confirm("确定删除这条记录吗？")) return; const { store, account } = currentAccount(); account.records = account.records.filter((record) => String(record.id) !== String(id)); persist(store); renderActiveView(); showToast("记录已删除"); }
function saveBudget(category) { const { store, account } = currentAccount(); account.budgets[selectedMonth] ||= {}; account.budgets[selectedMonth][category] = Number(document.querySelector(`[data-budget="${CSS.escape(category)}"]`).value || 0); persist(store); renderAnalysis(); showToast("预算已保存"); }
function exportBackup() { const blob = new Blob([JSON.stringify(currentAccount().account, null, 2)], { type: "application/json" }), link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `情绪稳定-${localMonth()}.json`; link.click(); URL.revokeObjectURL(link.href); }
document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => setView(button.dataset.view)));
$("#monthInput").addEventListener("change", (event) => { selectedMonth = event.target.value || localMonth(); renderActiveView(); });
$("#openAddBtn").addEventListener("click", openExpenseDialog); $("#closeExpenseBtn").addEventListener("click", () => $("#expenseDialog").close()); $("#exportBtn").addEventListener("click", exportBackup);
$("#majorInput").innerHTML = Object.keys(CATEGORIES).map((category) => `<option>${category}</option>`).join(""); $("#majorInput").addEventListener("change", fillMinorCategories); $("#minorInput").addEventListener("change", (event) => $("#customMinorField").classList.toggle("hidden", event.target.value !== "__custom"));
$("#expenseForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget), amount = Number(form.get("amount")); if (!(amount > 0)) return showToast("请输入有效金额"); const minor = form.get("minor") === "__custom" ? $("#minorCustomInput").value.trim() : form.get("minor"); if (!minor) return showToast("请输入小类名称"); const { store, account } = currentAccount(); account.records.push({ id: crypto.randomUUID?.() || String(Date.now()), date: form.get("date"), amount, major: form.get("major"), minor, necessity: form.get("necessity"), oneTime: form.get("oneTime") === "on", note: form.get("note").trim() }); persist(store); event.currentTarget.reset(); fillMinorCategories(); $("#expenseDialog").close(); renderActiveView(); showToast("记录已保存"); });
currentAccount(); fillMinorCategories(); setView("overview");
if ("serviceWorker" in navigator && location.protocol.startsWith("http")) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js"));
